main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Readings
    url: /reading/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: Classes
    url: /class/
    weight: 5

reading:
  - name: "Reading and references"
    url: /reading/

class:
  - name: "Class details"
    url: /class/
#    weight: 1
#   - name: RStudio.cloud
#     url: https://rstudio.cloud/
#     weight: 7
# assignment:
#   - name: Code
#     weight: 1
#   - name: Problem sets
#     weight: 2
