---
title: "Section 3: Data representations for neural network, Keras, Tensorflow"
# linktitle: "1. Introduction to RStudio and Images"
date: "2025-01-27"
class_date: "2025-01-27"
draft: false
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 3
type: docs
weight: 1
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Slides

### Foundations of Deep learning, Mathematical definitions, Data representation

<a href="../../slides/02b_data_tensorflow_gradient.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/02b_data_tensorflow_gradient.html#1')
```

<a href="../../slides/02b_data_tensorflow_gradient.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03a_keras_tensorflow.html#1')
```

<a href="../../slides/03b_Model_optimization.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03b_Model_optimization.html#1')
```

###  Introduction to Keras and Tensorflow

Tensor data types, Keras API, [RMarkdown](../../slides/code/ch03_Tensorflow_Introduction_code.Rmd)

